spring:
  datasource:
    url: ${USERS_DATABASE_URL}
    username: ${USERS_DATABASE_USERNAME}
    password: ${USERS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  mvc:
    servlet:
      path: /api
